---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: ceph
    compoent: secrets
  name: ceph-mds
spec:
  replicas: 1
  template:
    metadata:
      name: ceph-mds
      labels:
        app: ceph
        compoent: secrets
    spec:
      serviceAccount: default
      containers:
        - name: main
          image: docker.io/kollakube/centos-binary-ceph-init-k8s:4.0.0
          imagePullPolicy: Always
          command:
            - tail
            - -f
            - /dev/null
          volumeMounts:
            - name: ceph-key.py
              mountPath: /opt/ceph/ceph-key.py
              subPath: ceph-key.py
              readOnly: true
      volumes:
        - name: ceph-key.py
          configMap:
            name: ceph-key.py
