apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    version: v4.0.0
  name: ceph-secret-generator
  namespace: ceph
spec:
  template:
    metadata:
      labels:
        version: v4.0.0
      name: ceph-secret-generator
      namespace: ceph
    spec:
      containers:
        - name: ceph-secret-generator
          image: docker.io/kollakube/centos-binary-ceph-init-k8s:4.0.0
          imagePullPolicy: Always
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: osd_cluster_network
              value: 10.192.0.0/10
            - name: osd_public_network
              value: 10.192.0.0/10
          command:
            - /bin/bash
            - -ec
            - |
              cd /opt/kolla-k8s-ceph/generator
              ./generate-secrets.sh all `./generate-secrets.sh fsid`
              kubectl create secret generic ceph-conf-combined --from-file=ceph.conf --from-file=ceph.client.admin.keyring --from-file=ceph.mon.keyring --namespace=${MY_POD_NAME}
              kubectl create secret generic ceph-bootstrap-rgw-keyring --from-file=ceph.keyring=ceph.rgw.keyring --namespace=${MY_POD_NAME}
              kubectl create secret generic ceph-bootstrap-mds-keyring --from-file=ceph.keyring=ceph.mds.keyring --namespace=${MY_POD_NAME}
              kubectl create secret generic ceph-bootstrap-osd-keyring --from-file=ceph.keyring=ceph.osd.keyring --namespace=${MY_POD_NAME}
              kubectl create secret generic ceph-client-key --from-file=ceph-client-key --namespace=${MY_POD_NAME}
              cat > /tmp/keys.yaml <<EOF
              apiVersion: v1
              kind: Secret
              metadata:
                name: "pvc-ceph-conf-combined-storageclass"
              type: kubernetes.io/rbd
              data:
                key: |
                  $(kubectl get secret ceph-client-key --namespace=${MY_POD_NAME} -o json | jq -r '.data | .[]')
              EOF
              kubectl create --namespace ceph -f /tmp/keys.yaml
              cat > /tmp/keys.yaml <<EOF
              apiVersion: v1
              kind: Secret
              metadata:
                name: "pvc-ceph-client-key"
              type: kubernetes.io/rbd
              data:
                key: |
                  $(kubectl get secret ceph-client-key --namespace=${MY_POD_NAME} -o json | jq -r '.data | .[]')
              EOF
              kubectl create --namespace default -f /tmp/keys.yaml
      restartPolicy: OnFailure
